sudo: "required"

before_install:
  - chmod +x gradlew

install: true
language: java

jdk: oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/


global: GRADLE_OPTS="-Xmx2048m"
before_script: chmod +x gradlew
script:
- ./gradlew junit_test:junitPlatformTest #--stacktrace --debug

